name: Production Tests

on:
  workflow_dispatch:
  push:
    paths: 
    - '.github/workflows/production-tests.yml'
    branches: 
    - '*'
  schedule:
    - cron: '0 8 * * *'

jobs:

  test:

    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [
          ubuntu-20.04,
          ubuntu-22.04,
          macos-12,
          macos-13,
          macos-12-xl,
          macos-13-xl,
          windows-2019,
          windows-2022
        ]

    steps:
    - uses: actions/checkout@v4

    - name: Install gfic
      run: dotnet tool install --global gfic

    - name: Run with dotnet
      run: gfic --input ../../images/original/ --effect all --no-logging
      working-directory: src/gfic
