name: Production Tests

on:
  push:
    paths: 
    - '.github/workflows/production-tests.yml'
    branches: 
    - '*'
  schedule:
    - cron: '0 8 * * *'

jobs:

  test:

    name: Tests
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.os == 'macos-11.0' }}
    strategy:
      fail-fast: false
      matrix:
        os: [
          ubuntu-20.04,
          ubuntu-18.04,
          ubuntu-16.04,
          macos-11.0,
          macos-10.15,
          windows-2019,
          windows-2016
        ]

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1

    - name: Install gfic
      run: dotnet tool install --global gfic

    - name: Run with dotnet
      run: gfic --input ../../images/original/ --effect all --no-logging
      working-directory: src/gfic