name: Smoke Tests

on: [push]

jobs:

  test:

    name: Tests
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.os == 'macos-11.0' }}
    strategy:
      matrix:
        os: [
          ubuntu-latest,
          windows-latest,
          macos-latest
        ]

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1

    - name: Run with dotnet
      run: dotnet run --configuration Release -- --input ../../images/original/ --effect all --no-logging
      working-directory: src/gfic